title: Yohann Bertrand # your name (or website title) here
logo: "/images/Photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Physics Graduates 
  <br><br>
  Aspiring Data Scientist
  <br><br>
  <a href="https://1drv.ms/f/s!Av-tPMj3YiovgZTkWvTZFMCWCuWw04M?e=zB9BOb">My Curiculum Vitae</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/yohann-bertrand-11282722a/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
